linters-settings:
  funlen:
    lines: 100
    statements: 50

linters:
  enable:
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - gofmt
    - gochecknoinits
    - goconst
    - gocritic
    - gomoddirectives
    - goprintffuncname
    - gosec
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - paralleltest
    - prealloc
    - tagliatelle
    - unconvert
