version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gomi-info-db
    ports:
      - 3306:3306
    networks:
      - external
networks:
  external:
    driver: bridge
    internal: false
    name: gomiinfo-network
