version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gomi-info-db
    ports:
      - 3306:3306
    networks:
      - external

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - db
    command:
      [
        "-database",
        "mysql://root:password@tcp(db:3306)/gomi-info-db",
        "-path",
        "/migrations",
        "up",
      ]
    volumes:
      - ./migrations:/migrations
    networks:
      - external

networks:
  external:
    driver: bridge
    internal: false
    name: gomiinfo-network
