AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  Role:
    Type: String
    Description: Role arn
  MySQLUser:
    Type: String
    Description: MySQL user
  MySQLRootPassword:
    Type: String
    Description: MySQL root password
  MySQLHost:
    Type: String
    Description: MySQL host
  MySQLDatabase:
    Type: String
    Description: MySQL database name
  ChannelSecret:
    Type: String
    Description: LINE Bot Channel Secret
  ChannelToken:
    Type: String
    Description: LINE Bot Channel Token

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Environment:
      Variables:
        MYSQL_USER: !Ref MySQLUser
        MYSQL_ROOT_PASSWORD: !Ref MySQLRootPassword
        MYSQL_HOST: !Ref MySQLHost
        MYSQL_DATABASE: !Ref MySQLDatabase
Resources:
  HealthCheckFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/handler/health/
      Handler: health
      Runtime: go1.x
      Role: !Ref Role
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /health
            Method: GET
  GarbageDayInfoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/handler/garbage-day-info/
      Handler: garbage-day-info
      Runtime: go1.x
      Role: !Ref Role
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /garbage-day-info
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          CHANNEL_SECRET: !Ref ChannelSecret
          CHANNEL_TOKEN: !Ref ChannelToken
  ImportCsvToDbFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/batch/import_csv_to_db/
      Handler: import_csv_to_db
      Runtime: go1.x
      Role: !Ref Role
      Architectures:
        - x86_64
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            # 日本時間 0時に実行
            Schedule: rate(2 hours)
Outputs:
  ApiGatewayUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
